Stock_names = {'GME': 'GameStop Corp.',
 'AMZN': 'Amazon.com, Inc.',
 'SPY': 'SPDR S&P 500 ETF Trust',
 'XLF': 'Financial Select Sector SPDR Fund',
 'AAPL': 'Apple Inc.',
 'PFE': 'Pfizer Inc.',
 'AAL': 'American Airlines Group Inc.',
 'UBER': 'Uber Technologies, Inc.',
 'UUP': 'Invesco DB US Dollar Index Bullish Fund',
 'PEP': 'PepsiCo, Inc.',
 'GOOG': 'Alphabet Inc.',
 'MMM': '3M Company',
 'NTR': 'Nutrien Ltd.',
 'DKNG': 'DraftKings Inc.',
 'MDB': 'MongoDB, Inc.',
 'UWMC': 'UWM Holdings Corporation',
 'UPS': 'United Parcel Service, Inc.',
 'PLTR': 'Palantir Technologies Inc.',
 'SQ': 'Block, Inc.',
 'VXX': 'iPath Series B S&P 500 VIX Short-Term Futures ETN',
 'WMT': 'Walmart Inc.',
 'CVX': 'Chevron Corporation',
 'FCEL': 'FuelCell Energy, Inc.',
 'DWAC': 'Digital World Acquisition Corp.',
 'VALE': 'Vale S.A.',
 'MO': 'Altria Group, Inc.',
 'MU': 'Micron Technology, Inc.',
 'HD': 'The Home Depot, Inc.',
 'SHY': 'iShares 1-3 Year Treasury Bond ETF',
 'RRC': 'Range Resources Corporation',
 'ENPH': 'Enphase Energy, Inc.',
 'LC': 'LendingClub Corporation',
 'JKS': 'JinkoSolar Holding Co., Ltd.',
 'VUZI': 'Vuzix Corporation',
 'BKKT': 'Bakkt Holdings, Inc.',
 'BNO': 'United States Brent Oil Fund, LP',
 'LMT': 'Lockheed Martin Corporation',
 'WFC': 'Wells Fargo & Company',
 'CRWD': 'CrowdStrike Holdings, Inc.',
 'MRK': 'Merck & Co., Inc.',
 'SLV': 'iShares Silver Trust',
 'QCOM': 'QUALCOMM Incorporated',
 'TSLA': 'Tesla, Inc.',
 'SOL': 'ReneSola Ltd',
 'ARDX': 'Ardelyx, Inc.',
 'MOS': 'The Mosaic Company',
 'QS': 'QuantumScape Corporation',
 'MSFT': 'Microsoft Corporation',
 'TGT': 'Target Corporation',
 'META': 'Meta Platforms, Inc.',
 'ABBV': 'AbbVie Inc.',
 'TWTR': 'Twitter, Inc.',
 'RKT': 'Rocket Companies, Inc.',
 'RBLX': 'Roblox Corporation',
 'QQQ': 'Invesco QQQ Trust',
 'IEI': 'iShares 3-7 Year Treasury Bond ETF',
 'NFLX': 'Netflix, Inc.',
 'CCJ': 'Cameco Corporation',
 'F': 'Ford Motor Company',
 'IEF': 'iShares 7-10 Year Treasury Bond ETF',
 'SONO': 'Sonos, Inc.',
 'PYPL': 'PayPal Holdings, Inc.',
 'IBM': 'International Business Machines Corporation',
 'AMD': 'Advanced Micro Devices, Inc.',
 'AMC': 'AMC Entertainment Holdings, Inc.',
 'XLE': 'Energy Select Sector SPDR Fund',
 'XOM': 'Exxon Mobil Corporation',
 'SPI': 'SPI Energy Co., Ltd.',
 'XLV': 'Health Care Select Sector SPDR Fund',
 'CLSK': 'CleanSpark, Inc.',
 'COIN': 'Coinbase Global, Inc.',
 'ASAN': 'Asana, Inc.',
 'SBUX': 'Starbucks Corporation',
 'TLT': 'iShares 20+ Year Treasury Bond ETF',
 'KR': 'The Kroger Co.',
 'RTX': 'Raytheon Technologies Corporation',
 'AFRM': 'Affirm Holdings, Inc.',
 'GSL': 'Global Ship Lease, Inc.',
 'WBA': 'Walgreens Boots Alliance, Inc.',
 'UNG': 'United States Natural Gas Fund, LP',
 'BA': 'The Boeing Company',
 'CMRE': 'Costamare Inc.',
 'GE': 'General Electric Company',
 'INTU': 'Intuit Inc.',
 'SNAP': 'Snap Inc.',
 'NVDA': 'NVIDIA Corporation',
 'CTVA': 'Corteva, Inc.',
 'AA': 'Alcoa Corporation',
 'DIS': 'The Walt Disney Company',
 'CSCO': 'Cisco Systems, Inc.',
 'CVS': 'CVS Health Corporation',
 'CHGG': 'Chegg, Inc.',
 'KO': 'The Coca-Cola Company',
 'ICLN': 'iShares Global Clean Energy ETF',
 'CTRA': 'Coterra Energy Inc.',
 'SNOW': 'Snowflake Inc.',
 'FANG': 'Diamondback Energy, Inc.',
 'LI': 'Li Auto Inc.',
 'RUN': 'Sunrun Inc.',
 'TSN': 'Tyson Foods, Inc.',
 'ROKU': 'Roku, Inc.',
 'IWM': 'iShares Russell 2000 ETF',
 'SPWR': 'SunPower Corporation',
 'LULU': 'Lululemon Athletica Inc.',
 'OXY': 'Occidental Petroleum Corporation',
 'TBT': 'ProShares UltraShort 20+ Year Treasury',
 'C': 'Citigroup Inc.',
 'GLD': 'SPDR Gold Shares',
 'LCID': 'Lucid Group, Inc.',
 'WEAT': 'Teucrium Wheat Fund',
 'ABNB': 'Airbnb, Inc.',
 'V': 'Visa Inc.',
 'X': 'United States Steel Corporation',
 'MARA': 'Marathon Digital Holdings, Inc.',
 'EOG': 'EOG Resources, Inc.',
 'CLX': 'The Clorox Company',
 'JPM': 'JPMorgan Chase & Co.',
 'K': 'Kellogg Company',
 'DCFC': 'Tritium DCFC Limited',
 'TMV': 'Direxion Daily 20+ Year Treasury Bear 3X Shares',
 'SONY': 'Sony Group Corporation',
 'HOOD': 'Robinhood Markets, Inc.',
 'SPOT': 'Spotify Technology S.A.'}